name: Verify Dockerfile Build

on:
  pull_request:
    paths:
      - 'docker/dev/Dockerfile'
      - 'install-dependencies.sh'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            docker/dev/Dockerfile
            install-dependencies.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/dev/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
